### ISSUE TITLE
Nexus 4 build using aosp-9.0 branch stuck in bootloop

### ISSUE THREAD

**Issue by v-secure** [Unlegacy-Android/android_hardware_qcom_display#1]
My intention was to reproduce the build found at: https://forum.xda-developers.com/devdb/project/?id=20161#downloads. When flashed to the device, this works very nicely.

repo init -u git://github.com/Unlegacy-Android/android.git -b aosp-9.0
repo sync -c -f --force-sync --no-tag --no-clone-bundle -j$(nproc --all) --optimized-fetch --prune
lunch ua_mako-userdebug
make -j16

The device tries repeatedly to boot but it runs into this issue: "null pointer dereference" when calling "/system/vendor/lib/hw/hwcomposer.msm8960.so (hwc_prepare(hwc_composer_device_1*, unsigned int, hwc_display_contents_1**)+32)"
[boot_issue.txt](https://github.com/Unlegacy-Android/android_hardware_qcom_display/files/2905419/boot_issue.txt)

**Comment by clamor-s** [comment]
@v-secure issue is fixed

**Comment by v-secure** [comment]
Thank you for the heads up @clamor95 ; I've pulled the most recent sources and the display issue seems to be fixed; however I still cannot boot the build; I encounter the following issue with NFC:
03-25 13:21:06.079 F/DEBUG   ( 3468): pid: 3450, tid: 3450, name: com.android.nfc  >>> com.android.nfc <<<
03-25 13:21:06.079 F/DEBUG   ( 3468): signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
03-25 13:21:06.079 F/DEBUG   ( 3468): Abort message: 'nfc_config.cc:49] Check failed: config_path != "" '
03-25 13:21:06.080 F/DEBUG   ( 3468):     r0  00000000  r1  00000d7a  r2  00000006  r3  00000008
03-25 13:21:06.080 F/DEBUG   ( 3468):     r4  00000d7a  r5  00000d7a  r6  be8d4f34  r7  0000010c
03-25 13:21:06.080 F/DEBUG   ( 3468):     r8  00000002  r9  a979c760  r10 be8d5000  r11 a95ed40e
03-25 13:21:06.080 F/DEBUG   ( 3468):     ip  00000041  sp  be8d4f20  lr  a9bf2ffd  pc  a9bead6e
03-25 13:21:06.332 F/DEBUG   ( 3468): 
03-25 13:21:06.332 F/DEBUG   ( 3468): backtrace:
03-25 13:21:06.332 F/DEBUG   ( 3468):     #00 pc 0001cd6e  /system/lib/libc.so (abort+58)
03-25 13:21:06.332 F/DEBUG   ( 3468):     #01 pc 00357203  /system/lib/libart.so (art::Runtime::Abort(char const*)+950)
03-25 13:21:06.332 F/DEBUG   ( 3468):     #02 pc 000071c3  /system/lib/libbase.so (android::base::LogMessage::~LogMessage()+506)
03-25 13:21:06.332 F/DEBUG   ( 3468):     #03 pc 000a60dc  /system/lib/libnfc-nci.so (NfcConfig::loadConfig()+1176)
03-25 13:21:06.332 F/DEBUG   ( 3468):     #04 pc 000a625c  /system/lib/libnfc-nci.so (NfcConfig::getInstance()+124)

Do you have any idea how this can be addressed? Am I missing something? After completing the build I just run 'fastboot flashall' to flash boot, recovery & system.

**Comment by clamor-s** [comment]
@v-secure you didn't pick gerrit commits, alternatively, you can exclude NFC from build.

**Comment by v-secure** [comment]
Thank you for the reply @clamor95, unfortunately I'm new to these notions, so can you share some more details? I'm familiar with AOSP but not so much with custom builds and troubleshooting build/boot.

I've treated this build as a regular AOSP build. Do I need to do something special with it in terms of building or flashing? Unlegacy Android from branch aosp_8.0 worked well, do I need to do some extra things for aosp_9.0?

**Comment by clamor-s** [comment]
@v-secure work with Pie isn't finished yet. Write me an email, I'll tell what to do to fix NFC and MTP connection in your build.

**Comment by v-secure** [comment]
closing this as fixed; the issue has been addressed in commit: 6cb019f83f4ebf35bf75cd2f18be7714eeabf03e
